add support for Raspberry Pi Pico
radiolib-org/RadioBoards pull request #2
Opened 2024-06-03 02:35 UTC by K4KDR

added support for Raspberry Pi Pico microcontroller in 'contributed' folder.

** ref. the command syntax that is used w/ this board:

`SX1262 radio = new Module(3, 20, 15, 2, SPI1, RADIOLIB_DEFAULT_SPI_SETTINGS);`

... can someone please help with how (or "if") to document any **custom SPI** lines needed in

`src/contributed/RaspberryPi/PI_PICO.h`

... I'm not sure what the correct syntax would be given the command parameters that are used in the 'new Module' command.

Thank you!

2024-06-03 16:34 UTC, jgromes requested changes
Thank you! I left some comments.

Also, could you please add a section for the wireless module type? I added that in the latest commit.

```
#if RADIOLIB_SUPPORT_ENABLED
  #define Radio       SX1262
#endif
```

2024-06-03 16:34 UTC, jgromes commented on src/contributed/RaspberryPi/PI_PICO.h
> +SPI1.setRX(12);          \       // ~
I think it would be better to use the defined macros here, e.g. `RADIO_SPI.setSCK(RADIO_SCK);` instead

2024-06-03 16:34 UTC, jgromes commented on src/contributed/RaspberryPi/PI_PICO.h
> +digitalWrite(3, HIGH);   \       // ~
This is redundant, RadioLib initializes the NSS.

2024-06-03 16:34 UTC, jgromes commented on src/contributed/RaspberryPi/PI_PICO.h
> +RADIO_SPI1.begin(false);         // from https://github.com/jgromes/RadioLib/issues/729
This should probably be `RADIO_SPI.begin(false);`, I'm guessing a typo?

2024-06-03 18:25 UTC, jgromes approved these changes

2024-06-03 18:25 UTC, merged

2024-06-03 18:25 UTC, jgromes commented
All looks good now - merged, thank you!

2025-03-19 22:06 UTC, serialrf433 commented
This merged PR opens up the question if just any generic SBC that have no RadioLib-RF by default would get merged here. I was first expecting this Repo to be for OEM-connected devices. Like TTGO and other that have RF connected(soldered) to them when you get them.
If some DIY connected things on a breadboard are done, then its always up to the users to configure the pins they connected the RF to.

What is the opinion of others on this topic?

2025-03-20 06:17 UTC, jgromes commented
@serialrf433 this is definitely not as clear-cut as other devices, however, I think this is justified because the Pico has a well-defined shield format. So far I know only of Waveshare radio shield for it. So granted, it might have been better to name this "Waveshare LoRa Raspberry Pi Pico shield" (and we might revisit that naming if conflicts with other Pico shields in the future arise), but the code remains the same.

The same however does not apply to any other breadboard-based design.