Add support for Adafruit Feather RP2040 RFM
radiolib-org/RadioBoards pull request #4
Opened 2024-07-02 17:13 UTC by timmbogner

Hope everything looks okay!

2024-07-02 18:10 UTC, jgromes requested changes
Thank you for the contribution! I left one (minor) comment. Ijn addition, would it also be possible to add `RADIO_BOARD_FEATHER_RP2040` to `keywords.txt`? Keep in mind the file needs true tabs, not spaces.

2024-07-02 18:10 UTC, jgromes commented on src/RadioBoards.h
> +#if defined (RADIO_BOARDS_DEBUG)
I propose to keep it as it was - the intention (admittedly undocumented) was to have the macros decide on 0/1, same as `RADIOLIB_DEBUG`.

2024-07-02 18:19 UTC, StevenCellist commented
@jgromes how do you envision discerning between 'contributed' and 'maintained'? Would maintained only include boards that are tested by RadioLib contributors? In my own opinion, if users can provide a debug log showing a handful of LoRaWAN uplinks & downlink, that would be OK as well to move a board to maintained, because if something is wrong with the radio, LW won't work. But it quite depends on the definition of 'maintained'.

2024-07-02 18:54 UTC, timmbogner commented
@StevenCellist I was also wondering if there was a good method to verify the configuration. I'm not using LoRaWAN, so a different method of proof would work better for me. For this, I only verified that it initialized.

2024-07-02 18:57 UTC, jgromes commented
@StevenCellist you are right that it's not a completely clear distinction between the two ... so far I have settled on two criteria for maintained boards:

1. Verified by RadioLib org members
2. Can be quickly tested when users report issues

The first point can be satisfied by a log showing working communication, be it LoRaWAN or P2P (I agree that LoRaWAN OTAA+uplink is a nice end-to-end test). The second one is trickier, because it requires some sort of access to the hardware. So if we move a board from contributed to maintained, and then there's a problem, we might not have a way to replicate the issue.

But again, the distinction is not very clear, we may revisit this separation (or drop it altogether) at a later point.

2024-07-02 21:52 UTC, StevenCellist commented
@jgromes sure, looks fair to me. Thread hijack closed ;)

2024-07-03 15:38 UTC, jgromes approved these changes

2024-07-03 15:39 UTC, merged

2024-07-03 15:39 UTC, jgromes commented
All looks good now - merged, thank you!